package com.encorepay.utilities;

import java.io.File;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Properties;

import jakarta.mail.*;
import jakarta.mail.internet.*;
import jakarta.activation.*;

public final class EmailSender {

    private EmailSender() {
    }

    public static void sendEmailWithAttachment(
            String smtpHost,
            String smtpPort,
            String username,
            String password,
            String fromEmail,
            String toEmails,
            String pdfFilePath) throws MessagingException {

        if (smtpHost == null || smtpHost.isBlank()) {
            throw new IllegalArgumentException("SMTP host must not be blank.");
        }
        if (smtpPort == null || smtpPort.isBlank()) {
            throw new IllegalArgumentException("SMTP port must not be blank.");
        }
        if (fromEmail == null || fromEmail.isBlank()) {
            throw new IllegalArgumentException("From email must not be blank.");
        }
        if (toEmails == null || toEmails.isBlank()) {
            throw new IllegalArgumentException("To email must not be blank.");
        }
        if (pdfFilePath == null || pdfFilePath.isBlank()) {
            throw new IllegalArgumentException("PDF file path must not be blank.");
        }

        File pdfFile = new File(pdfFilePath);
        if (!pdfFile.exists()) {
            throw new IllegalArgumentException("PDF file does not exist: " + pdfFilePath);
        }

        // SMTP properties
        Properties props = new Properties();
        props.put("mail.smtp.host", smtpHost);
        props.put("mail.smtp.port", smtpPort);
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");

        // Create session
        Session session = Session.getInstance(props, new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });

        // Create message
        Message message = new MimeMessage(session);
        message.setFrom(new InternetAddress(fromEmail));

        // Parse multiple recipients
        InternetAddress[] toAddresses = InternetAddress.parse(toEmails);
        message.setRecipients(Message.RecipientType.TO, toAddresses);

        // Subject
        String reportDate = LocalDate.now().format(DateTimeFormatter.ofPattern("d MMM yyyy"));
        message.setSubject("Daily Job Status Report - " + reportDate);

        // Create multipart message
        Multipart multipart = new MimeMultipart();

        // Email body
        String reportTime = LocalDateTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss"));
        String bodyText = "Hello Team,\n\n" +
                "Please find attached the Daily Job Status Report generated by EncorePay Automation.\n\n" +
                "Report Date: " + reportDate + "\n" +
                "Generated Time: " + reportTime + "\n\n" +
                "Regards,\n" +
                "Laxman Kunwar";

        MimeBodyPart textPart = new MimeBodyPart();
        textPart.setText(bodyText);
        multipart.addBodyPart(textPart);

        // Attachment
        MimeBodyPart attachmentPart = new MimeBodyPart();
        DataSource source = new FileDataSource(pdfFile);
        attachmentPart.setDataHandler(new DataHandler(source));
        attachmentPart.setFileName(pdfFile.getName());
        multipart.addBodyPart(attachmentPart);

        // Set content
        message.setContent(multipart);

        // Send message
        Transport.send(message);
    }
}
